### PR TITLE
Create selamschap2.txt

### PR DESCRIPTION
**Pull request by selamb12**
this is my chapt 2 work

### CODE REVIEW

**Review by Feye12 — CHANGES_REQUESTED** [review]
can you add more doc

**Review by moemerga — APPROVED** [review]
merge approved.

**Comment by moemerga** [comment]
looks closed.

**Comment by yimers** [comment]
very Good Job Dave !!!

**Comment by moemerga** [comment]
file reviewed.

**Review by selamb12 — COMMENTED** [review]
looks great now

**Pull request closed without merging**
